[2024-06-11T22:18:53.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T22:18:53.910+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.delete_temp_file manual__2024-06-11T22:18:48.629603+00:00 map_index=1 [queued]>
[2024-06-11T22:18:53.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.delete_temp_file manual__2024-06-11T22:18:48.629603+00:00 map_index=1 [queued]>
[2024-06-11T22:18:53.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T22:18:53.938+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_each_invoice.delete_temp_file> on 2024-06-11 22:18:48.629603+00:00
[2024-06-11T22:18:53.944+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1307) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T22:18:53.945+0000] {standard_task_runner.py:63} INFO - Started process 1308 to run task
[2024-06-11T22:18:53.945+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'process_each_invoice.delete_temp_file', 'manual__2024-06-11T22:18:48.629603+00:00', '--job-id', '236', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmpnrx3t6mc', '--map-index', '1']
[2024-06-11T22:18:53.946+0000] {standard_task_runner.py:91} INFO - Job 236: Subtask process_each_invoice.delete_temp_file
[2024-06-11T22:18:53.994+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.process_each_invoice.delete_temp_file manual__2024-06-11T22:18:48.629603+00:00 map_index=1 [running]> on host 678b3b027d57
[2024-06-11T22:18:54.098+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='process_each_invoice.delete_temp_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T22:18:48.629603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T22:18:48.629603+00:00'
[2024-06-11T22:18:54.099+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T22:18:54.100+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T22:18:54.100+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 41, in delete_temp_file
    delete_file = BashOperator(
                  ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 152, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseOperator.__init__() missing 1 required positional argument: 'task_id'
[2024-06-11T22:18:54.115+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=invoice2receipt, task_id=process_each_invoice.delete_temp_file, run_id=manual__2024-06-11T22:18:48.629603+00:00, map_index=1, execution_date=20240611T221848, start_date=20240611T221853, end_date=20240611T221854
[2024-06-11T22:18:54.128+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 236 for task process_each_invoice.delete_temp_file (BaseOperator.__init__() missing 1 required positional argument: 'task_id'; 1308)
[2024-06-11T22:18:54.160+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T22:18:54.176+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T22:18:54.181+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
