[2024-06-12T04:38:07.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T04:38:07.330+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:37:57.518455+00:00 map_index=2 [queued]>
[2024-06-12T04:38:07.346+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:37:57.518455+00:00 map_index=2 [queued]>
[2024-06-12T04:38:07.347+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T04:38:07.367+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_each_invoice.check_job_status> on 2024-06-12 04:37:57.518455+00:00
[2024-06-12T04:38:07.374+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5069) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T04:38:07.376+0000] {standard_task_runner.py:63} INFO - Started process 5074 to run task
[2024-06-12T04:38:07.377+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'process_each_invoice.check_job_status', 'manual__2024-06-12T04:37:57.518455+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmps3k2ppq_', '--map-index', '2']
[2024-06-12T04:38:07.378+0000] {standard_task_runner.py:91} INFO - Job 279: Subtask process_each_invoice.check_job_status
[2024-06-12T04:38:07.434+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:37:57.518455+00:00 map_index=2 [running]> on host 678b3b027d57
[2024-06-12T04:38:07.642+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='process_each_invoice.check_job_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T04:37:57.518455+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T04:37:57.518455+00:00'
[2024-06-12T04:38:07.644+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T04:38:07.859+0000] {logging_mixin.py:188} INFO - {'message': 'Failed to decode provided token'}
[2024-06-12T04:38:07.866+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T04:38:07.867+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 52, in check_job_status
    if inv_data["status"] == "DONE":
       ~~~~~~~~^^^^^^^^^^
KeyError: 'status'
[2024-06-12T04:38:07.899+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=invoice2receipt, task_id=process_each_invoice.check_job_status, run_id=manual__2024-06-12T04:37:57.518455+00:00, map_index=2, execution_date=20240612T043757, start_date=20240612T043807, end_date=20240612T043807
[2024-06-12T04:38:07.918+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 279 for task process_each_invoice.check_job_status ('status'; 5074)
[2024-06-12T04:38:07.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T04:38:08.005+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
