[2024-06-11T05:49:47.479+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T05:49:47.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.process_file manual__2024-06-11T05:49:44.715135+00:00 map_index=1 [queued]>
[2024-06-11T05:49:47.514+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.process_file manual__2024-06-11T05:49:44.715135+00:00 map_index=1 [queued]>
[2024-06-11T05:49:47.515+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T05:49:47.530+0000] {taskinstance.py:2330} INFO - Executing <Mapped(PythonOperator): process_file> on 2024-06-11 05:49:44.715135+00:00
[2024-06-11T05:49:47.535+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2112) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T05:49:47.537+0000] {standard_task_runner.py:63} INFO - Started process 2113 to run task
[2024-06-11T05:49:47.537+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'process_file', 'manual__2024-06-11T05:49:44.715135+00:00', '--job-id', '108', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpic95ygiu', '--map-index', '1']
[2024-06-11T05:49:47.538+0000] {standard_task_runner.py:91} INFO - Job 108: Subtask process_file
[2024-06-11T05:49:47.579+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.process_file manual__2024-06-11T05:49:44.715135+00:00 map_index=1 [running]> on host 678b3b027d57
[2024-06-11T05:49:47.668+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T05:49:44.715135+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T05:49:44.715135+00:00'
[2024-06-11T05:49:47.669+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T05:49:47.681+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T05:49:47.682+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: length_of_file() takes 1 positional argument but 39 were given
[2024-06-11T05:49:47.690+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=process_file, run_id=manual__2024-06-11T05:49:44.715135+00:00, map_index=1, execution_date=20240611T054944, start_date=20240611T054947, end_date=20240611T054947
[2024-06-11T05:49:47.703+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 108 for task process_file (length_of_file() takes 1 positional argument but 39 were given; 2113)
[2024-06-11T05:49:47.711+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T05:49:47.725+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T05:49:47.729+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
