[2024-06-12T04:48:05.223+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T04:48:05.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:47:58.026923+00:00 map_index=0 [queued]>
[2024-06-12T04:48:05.257+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:47:58.026923+00:00 map_index=0 [queued]>
[2024-06-12T04:48:05.258+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T04:48:05.270+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_each_invoice.check_job_status> on 2024-06-12 04:47:58.026923+00:00
[2024-06-12T04:48:05.275+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5252) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T04:48:05.276+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'process_each_invoice.check_job_status', 'manual__2024-06-12T04:47:58.026923+00:00', '--job-id', '300', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmpsntdrdhh', '--map-index', '0']
[2024-06-12T04:48:05.276+0000] {standard_task_runner.py:63} INFO - Started process 5253 to run task
[2024-06-12T04:48:05.277+0000] {standard_task_runner.py:91} INFO - Job 300: Subtask process_each_invoice.check_job_status
[2024-06-12T04:48:05.313+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:47:58.026923+00:00 map_index=0 [running]> on host 678b3b027d57
[2024-06-12T04:48:05.390+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='process_each_invoice.check_job_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T04:47:58.026923+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T04:47:58.026923+00:00'
[2024-06-12T04:48:05.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T04:48:05.728+0000] {logging_mixin.py:188} INFO - {'error': {'code': 'E2', 'message': 'Document with the provided UUID not found.', 'details': [{'code': '0', 'message': "Document UUID: ('4f2fa613-f3a3-4d28-b608-b98297fdd42c',)"}]}}
[2024-06-12T04:48:05.730+0000] {logging_mixin.py:188} INFO - ('4f2fa613-f3a3-4d28-b608-b98297fdd42c',) <class 'tuple'>
[2024-06-12T04:48:05.731+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T04:48:05.731+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 54, in check_job_status
    if inv_data["status"] == "DONE":
       ~~~~~~~~^^^^^^^^^^
KeyError: 'status'
[2024-06-12T04:48:05.771+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=invoice2receipt, task_id=process_each_invoice.check_job_status, run_id=manual__2024-06-12T04:47:58.026923+00:00, map_index=0, execution_date=20240612T044758, start_date=20240612T044805, end_date=20240612T044805
[2024-06-12T04:48:05.784+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 300 for task process_each_invoice.check_job_status ('status'; 5253)
[2024-06-12T04:48:05.813+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T04:48:05.826+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T04:48:05.830+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
