[2024-06-11T05:27:47.272+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T05:27:47.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.process_file manual__2024-06-11T05:27:42.534312+00:00 map_index=0 [queued]>
[2024-06-11T05:27:47.359+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.process_file manual__2024-06-11T05:27:42.534312+00:00 map_index=0 [queued]>
[2024-06-11T05:27:47.362+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T05:27:47.375+0000] {taskinstance.py:2330} INFO - Executing <Mapped(PythonOperator): process_file> on 2024-06-11 05:27:42.534312+00:00
[2024-06-11T05:27:47.381+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1802) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T05:27:47.383+0000] {standard_task_runner.py:63} INFO - Started process 1803 to run task
[2024-06-11T05:27:47.382+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'process_file', 'manual__2024-06-11T05:27:42.534312+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpbt0xobwz', '--map-index', '0']
[2024-06-11T05:27:47.384+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask process_file
[2024-06-11T05:27:47.421+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.process_file manual__2024-06-11T05:27:42.534312+00:00 map_index=0 [running]> on host 678b3b027d57
[2024-06-11T05:27:47.503+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='process_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T05:27:42.534312+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T05:27:42.534312+00:00'
[2024-06-11T05:27:47.514+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T05:27:47.525+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T05:27:47.528+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: length_of_file() takes 1 positional argument but 2 were given
[2024-06-11T05:27:48.089+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=process_file, run_id=manual__2024-06-11T05:27:42.534312+00:00, map_index=0, execution_date=20240611T052742, start_date=20240611T052747, end_date=20240611T052748
[2024-06-11T05:27:48.112+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task process_file (length_of_file() takes 1 positional argument but 2 were given; 1803)
[2024-06-11T05:27:48.120+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T05:27:48.134+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T05:27:48.138+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
