[2024-06-12T04:35:40.751+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T04:35:40.787+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:35:31.876457+00:00 map_index=1 [queued]>
[2024-06-12T04:35:40.805+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:35:31.876457+00:00 map_index=1 [queued]>
[2024-06-12T04:35:40.807+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-12T04:35:40.826+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_each_invoice.check_job_status> on 2024-06-12 04:35:31.876457+00:00
[2024-06-12T04:35:40.833+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5010) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T04:35:40.835+0000] {standard_task_runner.py:63} INFO - Started process 5011 to run task
[2024-06-12T04:35:40.836+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'process_each_invoice.check_job_status', 'manual__2024-06-12T04:35:31.876457+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmp96fj7tz3', '--map-index', '1']
[2024-06-12T04:35:40.837+0000] {standard_task_runner.py:91} INFO - Job 267: Subtask process_each_invoice.check_job_status
[2024-06-12T04:35:40.902+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:35:31.876457+00:00 map_index=1 [running]> on host 678b3b027d57
[2024-06-12T04:35:41.042+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='process_each_invoice.check_job_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T04:35:31.876457+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T04:35:31.876457+00:00'
[2024-06-12T04:35:41.044+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T04:35:41.282+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T04:35:41.284+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 52, in check_job_status
    if inv_data["status"] == "DONE":
       ~~~~~~~~^^^^^^^^^^
KeyError: 'status'
[2024-06-12T04:35:41.309+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=invoice2receipt, task_id=process_each_invoice.check_job_status, run_id=manual__2024-06-12T04:35:31.876457+00:00, map_index=1, execution_date=20240612T043531, start_date=20240612T043540, end_date=20240612T043541
[2024-06-12T04:35:41.329+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 267 for task process_each_invoice.check_job_status ('status'; 5011)
[2024-06-12T04:35:41.373+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T04:35:41.442+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T04:35:41.450+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
