[2024-06-11T04:03:33.259+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T04:03:33.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.loop_file manual__2024-06-11T04:03:31.265020+00:00 [queued]>
[2024-06-11T04:03:33.288+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.loop_file manual__2024-06-11T04:03:31.265020+00:00 [queued]>
[2024-06-11T04:03:33.289+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T04:03:33.303+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): loop_file> on 2024-06-11 04:03:31.265020+00:00
[2024-06-11T04:03:33.309+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=976) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T04:03:33.310+0000] {standard_task_runner.py:63} INFO - Started process 977 to run task
[2024-06-11T04:03:33.310+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'loop_file', 'manual__2024-06-11T04:03:31.265020+00:00', '--job-id', '67', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpd4rtghnq']
[2024-06-11T04:03:33.311+0000] {standard_task_runner.py:91} INFO - Job 67: Subtask loop_file
[2024-06-11T04:03:33.350+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.loop_file manual__2024-06-11T04:03:31.265020+00:00 [running]> on host 678b3b027d57
[2024-06-11T04:03:33.427+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='loop_file' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T04:03:31.265020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T04:03:31.265020+00:00'
[2024-06-11T04:03:33.428+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T04:03:33.438+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T04:03:33.446+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_hello_world.py", line 44, in loop_files
    with TaskGroup("section_1", tooltip="Tasks for section_1") as section_1:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/task_group.py", line 124, in __init__
    raise AirflowException("TaskGroup can only be used inside a dag")
airflow.exceptions.AirflowException: TaskGroup can only be used inside a dag
[2024-06-11T04:03:33.456+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=loop_file, run_id=manual__2024-06-11T04:03:31.265020+00:00, execution_date=20240611T040331, start_date=20240611T040333, end_date=20240611T040333
[2024-06-11T04:03:33.467+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 67 for task loop_file (TaskGroup can only be used inside a dag; 977)
[2024-06-11T04:03:33.485+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T04:03:33.497+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T04:03:33.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
