[2024-06-11T12:54:22.477+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T12:54:22.505+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.process_group.read_task manual__2024-06-11T12:54:20.229187+00:00 map_index=1 [queued]>
[2024-06-11T12:54:22.586+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.process_group.read_task manual__2024-06-11T12:54:20.229187+00:00 map_index=1 [queued]>
[2024-06-11T12:54:22.604+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T12:54:22.619+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_group.read_task> on 2024-06-11 12:54:20.229187+00:00
[2024-06-11T12:54:22.626+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=7395) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T12:54:22.627+0000] {standard_task_runner.py:63} INFO - Started process 7397 to run task
[2024-06-11T12:54:22.627+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'process_group.read_task', 'manual__2024-06-11T12:54:20.229187+00:00', '--job-id', '159', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpghpt86_4', '--map-index', '1']
[2024-06-11T12:54:22.629+0000] {standard_task_runner.py:91} INFO - Job 159: Subtask process_group.read_task
[2024-06-11T12:54:22.668+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.process_group.read_task manual__2024-06-11T12:54:20.229187+00:00 map_index=1 [running]> on host 678b3b027d57
[2024-06-11T12:54:22.738+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='process_group.read_task' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T12:54:20.229187+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T12:54:20.229187+00:00'
[2024-06-11T12:54:22.739+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T12:54:22.740+0000] {logging_mixin.py:188} INFO - MappedArgument(_input=DictOfListsExpandInput(value={'filename': XComArg(<Task(_PythonDecoratedOperator): read_files_task>)}), _key='filename') <class '***.models.expandinput.MappedArgument'>
[2024-06-11T12:54:22.741+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T12:54:22.742+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_hello_world.py", line 35, in read_task
    with open(str(filename)) as file:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: "MappedArgument(_input=DictOfListsExpandInput(value={'filename': XComArg(<Task(_PythonDecoratedOperator): read_files_task>)}), _key='filename')"
[2024-06-11T12:54:22.753+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=process_group.read_task, run_id=manual__2024-06-11T12:54:20.229187+00:00, map_index=1, execution_date=20240611T125420, start_date=20240611T125422, end_date=20240611T125422
[2024-06-11T12:54:22.764+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 159 for task process_group.read_task ([Errno 2] No such file or directory: "MappedArgument(_input=DictOfListsExpandInput(value={'filename': XComArg(<Task(_PythonDecoratedOperator): read_files_task>)}), _key='filename')"; 7397)
[2024-06-11T12:54:22.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T12:54:22.838+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T12:54:22.851+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
