[2024-06-12T04:56:28.503+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-12T04:56:28.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:56:21.410531+00:00 map_index=1 [queued]>
[2024-06-12T04:56:28.532+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:56:21.410531+00:00 map_index=1 [queued]>
[2024-06-12T04:56:28.534+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-12T04:56:28.548+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): process_each_invoice.check_job_status> on 2024-06-12 04:56:21.410531+00:00
[2024-06-12T04:56:28.557+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5392) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-12T04:56:28.558+0000] {standard_task_runner.py:63} INFO - Started process 5395 to run task
[2024-06-12T04:56:28.558+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'process_each_invoice.check_job_status', 'manual__2024-06-12T04:56:21.410531+00:00', '--job-id', '312', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmpc7uqfgo6', '--map-index', '1']
[2024-06-12T04:56:28.560+0000] {standard_task_runner.py:91} INFO - Job 312: Subtask process_each_invoice.check_job_status
[2024-06-12T04:56:28.597+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.process_each_invoice.check_job_status manual__2024-06-12T04:56:21.410531+00:00 map_index=1 [running]> on host 678b3b027d57
[2024-06-12T04:56:28.669+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='process_each_invoice.check_job_status' AIRFLOW_CTX_EXECUTION_DATE='2024-06-12T04:56:21.410531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-12T04:56:21.410531+00:00'
[2024-06-12T04:56:28.670+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-12T04:56:29.310+0000] {logging_mixin.py:188} INFO - {'status': 'PENDING', 'id': '2a3bbac6-449f-4c01-a206-b3f6687f3d02', 'fileName': 'sample-invoice-3.pdf', 'documentType': 'invoice', 'created': '2024-06-12T04:56:27.425826+00:00', 'clientId': 'default', 'languageCodes': ['xx'], 'schemaId': 'cf8cc8a9-1eee-42d9-9a3e-507a61baac23', 'schemaVersion': '1'}
[2024-06-12T04:56:29.313+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-12T04:56:29.314+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 60, in check_job_status
    raise Exception("Retry - Job is still pending")
Exception: Retry - Job is still pending
[2024-06-12T04:56:29.324+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=invoice2receipt, task_id=process_each_invoice.check_job_status, run_id=manual__2024-06-12T04:56:21.410531+00:00, map_index=1, execution_date=20240612T045621, start_date=20240612T045628, end_date=20240612T045629
[2024-06-12T04:56:29.334+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 312 for task process_each_invoice.check_job_status (Retry - Job is still pending; 5395)
[2024-06-12T04:56:29.376+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-12T04:56:29.409+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-12T04:56:29.418+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
