[2024-06-11T21:13:54.839+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T21:13:54.851+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:13:54.024663+00:00 [queued]>
[2024-06-11T21:13:54.858+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:13:54.024663+00:00 [queued]>
[2024-06-11T21:13:54.859+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T21:13:54.871+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): read_inv_frm_S3> on 2024-06-11 21:13:54.024663+00:00
[2024-06-11T21:13:54.875+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=408) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T21:13:54.876+0000] {standard_task_runner.py:63} INFO - Started process 409 to run task
[2024-06-11T21:13:54.876+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'invoice2receipt', 'read_inv_frm_S3', 'manual__2024-06-11T21:13:54.024663+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/invoice2receipt.py', '--cfg-path', '/tmp/tmpp2t3jgsn']
[2024-06-11T21:13:54.878+0000] {standard_task_runner.py:91} INFO - Job 216: Subtask read_inv_frm_S3
[2024-06-11T21:13:54.912+0000] {task_command.py:426} INFO - Running <TaskInstance: invoice2receipt.read_inv_frm_S3 manual__2024-06-11T21:13:54.024663+00:00 [running]> on host 678b3b027d57
[2024-06-11T21:13:54.969+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='invoice2receipt' AIRFLOW_CTX_TASK_ID='read_inv_frm_S3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T21:13:54.024663+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T21:13:54.024663+00:00'
[2024-06-11T21:13:54.970+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T21:13:54.977+0000] {base.py:84} INFO - Using connection ID 'AWS_connection' for task execution.
[2024-06-11T21:13:54.978+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='AWS_connection', conn_type='aws') credentials retrieved from login and password.
[2024-06-11T21:13:55.031+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T21:13:55.032+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/invoice2receipt.py", line 18, in read_inv_from_S3
    print(s3_hook.account_id)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 649, in account_id
    .get_caller_identity()["Account"]
     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1001, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1027, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 190, in sign
    auth = self.get_auth_instance(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/signers.py", line 314, in get_auth_instance
    raise botocore.exceptions.NoRegionError()
botocore.exceptions.NoRegionError: You must specify a region.
[2024-06-11T21:13:55.048+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=invoice2receipt, task_id=read_inv_frm_S3, run_id=manual__2024-06-11T21:13:54.024663+00:00, execution_date=20240611T211354, start_date=20240611T211354, end_date=20240611T211355
[2024-06-11T21:13:55.058+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 216 for task read_inv_frm_S3 (You must specify a region.; 409)
[2024-06-11T21:13:55.092+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T21:13:55.104+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T21:13:55.108+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
