[2024-06-11T03:28:31.072+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-11T03:28:31.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: hello_word.read_files_from_path manual__2024-06-11T03:28:29.151089+00:00 [queued]>
[2024-06-11T03:28:31.103+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: hello_word.read_files_from_path manual__2024-06-11T03:28:29.151089+00:00 [queued]>
[2024-06-11T03:28:31.104+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-11T03:28:31.118+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_files_from_path> on 2024-06-11 03:28:29.151089+00:00
[2024-06-11T03:28:31.124+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-11T03:28:31.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'hello_word', 'read_files_from_path', 'manual__2024-06-11T03:28:29.151089+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/simple_hello_world.py', '--cfg-path', '/tmp/tmpbfgcmtbx']
[2024-06-11T03:28:31.126+0000] {standard_task_runner.py:63} INFO - Started process 492 to run task
[2024-06-11T03:28:31.127+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask read_files_from_path
[2024-06-11T03:28:31.168+0000] {task_command.py:426} INFO - Running <TaskInstance: hello_word.read_files_from_path manual__2024-06-11T03:28:29.151089+00:00 [running]> on host 678b3b027d57
[2024-06-11T03:28:31.232+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Anudeep' AIRFLOW_CTX_DAG_ID='hello_word' AIRFLOW_CTX_TASK_ID='read_files_from_path' AIRFLOW_CTX_EXECUTION_DATE='2024-06-11T03:28:29.151089+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-11T03:28:29.151089+00:00'
[2024-06-11T03:28:31.233+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-11T03:28:31.250+0000] {base.py:84} INFO - Using connection ID 'invoices' for task execution.
[2024-06-11T03:28:31.253+0000] {logging_mixin.py:188} INFO - ['invoices', 'simple_hello_world.py', '__init__.py', '__pycache__']
[2024-06-11T03:28:31.254+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-11T03:28:31.254+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/simple_hello_world.py", line 30, in read_files_from_path
    files = os.listdir(os.path.join(os.getcwd(), hook.get_path()))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/airflow/dags/invoices/'
[2024-06-11T03:28:31.267+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=hello_word, task_id=read_files_from_path, run_id=manual__2024-06-11T03:28:29.151089+00:00, execution_date=20240611T032829, start_date=20240611T032831, end_date=20240611T032831
[2024-06-11T03:28:31.278+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 58 for task read_files_from_path ([Errno 2] No such file or directory: '/airflow/dags/invoices/'; 492)
[2024-06-11T03:28:31.301+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-11T03:28:31.314+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-11T03:28:31.318+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
